---
title: "project2"
author: "Rohan Chowla"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}
# Load the required library
library(shiny)

# Define UI for application
ui <- fluidPage(
  
  # Application title
  titlePanel("Final Project"),
  
  # Sidebar layout with input and output definitions
  sidebarLayout(
    
    # Sidebar panel for inputs
    sidebarPanel(
      
      # Tab selection
      tabsetPanel(
        tabPanel("Introduction", value = "intro"),
        tabPanel("Question 1", value = "q1"),
        tabPanel("Question 2", value = "q2"),
        tabPanel("Question 3", value = "q3")
      )
    ),
    
    # Main panel for displaying outputs
    mainPanel(
      # Output
      uiOutput("output")
    )
  )
)

# Define server logic
server <- function(input, output) {
  
  # Function to render output based on selected tab
  output$output <- renderUI({
    selected_tab <- input$tabsetPanel
    if (is.null(selected_tab)) {
      return(NULL)
    } else if (selected_tab == "intro") {
      # Render output for Intro
      fluidRow(
        column(12,
               h3("Introduction to dataset"),
               # Add your output elements for Question 1 here
        )
      )
    } else if (selected_tab == "q1") {
      # Render output for Question 1
      fluidRow(
        column(12,
               h3("Answer to Question 1"),
               # Add your output elements for Question 1 here
        )
      )
    } else if (selected_tab == "q2") {
      # Render output for Question 2
      fluidRow(
        column(12,
               h3("Answer to Question 2"),
               # Add your output elements for Question 2 here
        )
      )
    } else if (selected_tab == "q3") {
      # Render output for Question 3
      fluidRow(
        column(12,
               h3("Answer to Question 3"),
               # Add your output elements for Question 3 here
        )
      )
    }
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```